### ISSUE TITLE
Doesn't work on Windows due to missing dependency - fcntl

### ISSUE THREAD

**Issue by sarimak** [jamesls/flask-shelve#2]
Flask-Shelve module cannot be used on Windows because **fcntl** module from standard library is not available:

```
Traceback (most recent call last):
  File "***.py", line ***, in <module>
    from flask.ext import shelve
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\flask_shelve.py", line 4, in <module>
    import fcntl
ImportError: No module named 'fcntl'

c:\Users\***>python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fcntl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'fcntl'
```

Since Flask-Shelve uses fcntl.flock() just for mandatory write locking and advisory read locking, replacing it by an cross-platform alternative like **portalocker** should be feasible.

**Comment by sarimak** [comment]
Notes:
- portalocker requires a MSI from https://sourceforge.net/projects/pywin32/files/pywin32 to be installed (otherwise import win32con fails)
- os.open() and os.close() in Flask-Shelve needs to be replaced by standard open() and close() otherwise portalocker would try to extract Windows file handle from integer which fails
- lock syntax of portalocker is: portalocker.lock(fileno, portalocker.LOCK_SH) or portalocker.lock(fileno, portalocker.LOCK_EX), unlock syntax is: portalocker.unlock(fileno)

**Comment by sarimak** [comment]
Patch:

```
> diff flask_shelve_custom.py flask_shelve.py
3a4
> import fcntl
9,10d9
< import portalocker
<
113c112
<         fileno = open(self._filename, "wb")
---
>         fileno = os.open(self._filename, os.O_RDWR)
115c114
<         portalocker.lock(fileno, portalocker.LOCK_SH)
---
>         fcntl.flock(fileno, fcntl.LOCK_SH)
120c119
<         fileno = open(self._filename, "wb")
---
>         fileno = os.open(self._filename, os.O_RDWR)
122c121
<         portalocker.lock(fileno, portalocker.LOCK_EX)
---
>         fcntl.flock(fileno, fcntl.LOCK_EX)
127,128c126,127
<         portalocker.unlock(fileno)
<         fileno.close()
---
>         fcntl.flock(fileno, fcntl.LOCK_UN)
>         os.close(fileno)
131,132c130,131
<         portalocker.unlock(fileno)
<         fileno.close()
---
>         fcntl.flock(fileno, fcntl.LOCK_UN)
>         os.close(fileno)
```
